export default {
  LOADING: "HOME_LOADING",
  OVERALL: "HOME_OVERALL",
  OVERALL_SUCCESS: "HOME_OVERALL_SUCCESS",
  OVERALL_FAILURE: "HOME_OVERALL_FAILURE",
  AREA: "HOME_AREA",
  AREA_SUCCESS: "HOME_AREA_SUCCESS",
  AREA_FAILURE: "HOME_AREA_FAILURE",
  AREA_LIST: "HOME_AREA_LIST",
  AREA_LIST_FAILURE: "HOME_AREA_LIST_FAILURE",
  AREA_LIST_SUCCESS: "HOME_AREA_LIST_SUCCESS"
};
